"""portfolio 단순화

Revision ID: 0bbb617f58e3
Revises: 4e3c8d5b3b5a
Create Date: 2025-08-11 18:23:30.871339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0bbb617f58e3'
down_revision: Union[str, Sequence[str], None] = '4e3c8d5b3b5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'total_quantity')
    op.drop_column('portfolios', 'total_invested_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('total_invested_amount', mysql.DECIMAL(precision=20, scale=2), nullable=False, comment='총 투자금액'))
    op.add_column('portfolios', sa.Column('total_quantity', mysql.DECIMAL(precision=20, scale=0), nullable=False, comment='총 매수 수량'))
    # ### end Alembic commands ###
