"""remove_transaction_stats_from_virtual_balance

Revision ID: 0e6321424c47
Revises: b68e52d816cc
Create Date: 2025-09-09 23:32:53.210565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0e6321424c47'
down_revision: Union[str, Sequence[str], None] = 'b68e52d816cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('industry_code', sa.String(length=50), nullable=True, comment='업종 코드'))
    op.add_column('transactions', sa.Column('industry_display', sa.String(length=100), nullable=True, comment='업종명'))
    op.drop_column('virtual_balances', 'total_commission')
    op.drop_column('virtual_balances', 'total_sell_amount')
    op.drop_column('virtual_balances', 'total_tax')
    op.drop_column('virtual_balances', 'total_buy_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_balances', sa.Column('total_buy_amount', mysql.DECIMAL(precision=20, scale=2), nullable=False, comment='총 매수 금액'))
    op.add_column('virtual_balances', sa.Column('total_tax', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='총 세금'))
    op.add_column('virtual_balances', sa.Column('total_sell_amount', mysql.DECIMAL(precision=20, scale=2), nullable=False, comment='총 매도 금액'))
    op.add_column('virtual_balances', sa.Column('total_commission', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='총 수수료'))
    op.drop_column('transactions', 'industry_display')
    op.drop_column('transactions', 'industry_code')
    # ### end Alembic commands ###
