"""Portfolio 와 Order 를 1:n 관계로 설정

Revision ID: 48ab17309e7a
Revises: 5d3600b86857
Create Date: 2025-09-04 21:16:14.136075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48ab17309e7a'
down_revision: Union[str, Sequence[str], None] = '5d3600b86857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('portfolio_id', sa.String(length=36), nullable=True, comment='연결된 포트폴리오 ID'))
    op.create_index(op.f('ix_orders_portfolio_id'), 'orders', ['portfolio_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'portfolios', ['portfolio_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_portfolio_id'), table_name='orders')
    op.drop_column('orders', 'portfolio_id')
    # ### end Alembic commands ###
