"""watch list directory

Revision ID: 4aa95e87f643
Revises: 9e62fccaa8e6
Create Date: 2025-08-26 17:40:19.616799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4aa95e87f643'
down_revision: Union[str, Sequence[str], None] = '9e62fccaa8e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_directories',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='사용자 ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='디렉토리 이름'),
    sa.Column('description', sa.Text(), nullable=True, comment='디렉토리 설명'),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='표시 순서'),
    sa.Column('color', sa.String(length=20), nullable=True, comment='디렉토리 색상 (hex code)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('watch_lists', sa.Column('directory_id', sa.String(length=36), nullable=True, comment='디렉토리 ID'))
    op.alter_column('watch_lists', 'category',
               existing_type=mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=50),
               comment='카테고리 (구버전 호환)',
               existing_comment='카테고리',
               existing_nullable=True)
    op.create_foreign_key(None, 'watch_lists', 'watchlist_directories', ['directory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watch_lists', type_='foreignkey')
    op.alter_column('watch_lists', 'category',
               existing_type=mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=50),
               comment='카테고리',
               existing_comment='카테고리 (구버전 호환)',
               existing_nullable=True)
    op.drop_column('watch_lists', 'directory_id')
    op.drop_table('watchlist_directories')
    # ### end Alembic commands ###
