"""portfolio 와 virtual_balance 에서 확정값만 db 에 저장하게 변경

Revision ID: 4e3c8d5b3b5a
Revises: ba57019f51e7
Create Date: 2025-08-11 16:36:08.492460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4e3c8d5b3b5a'
down_revision: Union[str, Sequence[str], None] = 'ba57019f51e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'unrealized_profit_loss')
    op.drop_column('portfolios', 'current_value')
    op.drop_column('portfolios', 'unrealized_profit_loss_rate')
    op.alter_column('virtual_balances', 'invested_amount',
               existing_type=mysql.DECIMAL(precision=20, scale=2),
               comment='투자 금액(원가 기준 확정값)',
               existing_comment='투자 금액',
               existing_nullable=False)
    op.drop_column('virtual_balances', 'total_profit_loss')
    op.drop_column('virtual_balances', 'daily_profit_loss_rate')
    op.drop_column('virtual_balances', 'total_profit_loss_rate')
    op.drop_column('virtual_balances', 'total_portfolio_value')
    op.drop_column('virtual_balances', 'daily_profit_loss')
    op.drop_column('virtual_balances', 'total_asset_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_balances', sa.Column('total_asset_value', mysql.DECIMAL(precision=20, scale=2), nullable=False, comment='총 자산 가치 (현금 + 포트폴리오)'))
    op.add_column('virtual_balances', sa.Column('daily_profit_loss', mysql.DECIMAL(precision=20, scale=2), nullable=False, comment='일일 손익'))
    op.add_column('virtual_balances', sa.Column('total_portfolio_value', mysql.DECIMAL(precision=20, scale=2), nullable=False, comment='총 포트폴리오 가치'))
    op.add_column('virtual_balances', sa.Column('total_profit_loss_rate', mysql.DECIMAL(precision=5, scale=2), nullable=False, comment='총 손익률 (%)'))
    op.add_column('virtual_balances', sa.Column('daily_profit_loss_rate', mysql.DECIMAL(precision=5, scale=2), nullable=False, comment='일일 손익률 (%)'))
    op.add_column('virtual_balances', sa.Column('total_profit_loss', mysql.DECIMAL(precision=20, scale=2), nullable=False, comment='총 손익'))
    op.alter_column('virtual_balances', 'invested_amount',
               existing_type=mysql.DECIMAL(precision=20, scale=2),
               comment='투자 금액',
               existing_comment='투자 금액(원가 기준 확정값)',
               existing_nullable=False)
    op.add_column('portfolios', sa.Column('unrealized_profit_loss_rate', mysql.DECIMAL(precision=5, scale=2), nullable=True, comment='미실현 손익률 (%)'))
    op.add_column('portfolios', sa.Column('current_value', mysql.DECIMAL(precision=20, scale=2), nullable=True, comment='현재 평가금액'))
    op.add_column('portfolios', sa.Column('unrealized_profit_loss', mysql.DECIMAL(precision=20, scale=2), nullable=True, comment='미실현 손익'))
    # ### end Alembic commands ###
