"""move realized_profit_loss from order to transaction

Revision ID: 4f7473bdd1af
Revises: 5d8a1f3a
Create Date: 2025-09-05 12:33:26.451417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f7473bdd1af'
down_revision: Union[str, Sequence[str], None] = '5d8a1f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('realized_profit_loss', sa.Numeric(precision=20, scale=8), nullable=False, comment='누적 실현 손익 (현지통화)'))
    op.add_column('portfolios', sa.Column('krw_realized_profit_loss', sa.Numeric(precision=20, scale=2), nullable=False, comment='원화 환산 누적 실현 손익'))
    op.add_column('transactions', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')))
    op.add_column('transactions', sa.Column('realized_profit_loss', sa.Numeric(precision=20, scale=8), nullable=True, comment='실현 손익 (현지통화)'))
    op.add_column('transactions', sa.Column('krw_realized_profit_loss', sa.Numeric(precision=20, scale=2), nullable=True, comment='원화 환산 실현 손익'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'krw_realized_profit_loss')
    op.drop_column('transactions', 'realized_profit_loss')
    op.drop_column('transactions', 'updated_at')
    op.drop_column('portfolios', 'krw_realized_profit_loss')
    op.drop_column('portfolios', 'realized_profit_loss')
    # ### end Alembic commands ###
