"""portfolio, order 환율

Revision ID: 536869bfd17a
Revises: 5afaaf6b437f
Create Date: 2025-09-03 16:03:31.623260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '536869bfd17a'
down_revision: Union[str, Sequence[str], None] = '5afaaf6b437f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_executions', sa.Column('exchange_rate', sa.Numeric(precision=10, scale=4), nullable=True, comment='체결 시점 환율 (외화 -> KRW)'))
    op.add_column('order_executions', sa.Column('krw_execution_price', sa.Numeric(precision=20, scale=2), nullable=True, comment='원화 환산 체결가격'))
    op.add_column('order_executions', sa.Column('krw_execution_amount', sa.Numeric(precision=20, scale=2), nullable=True, comment='원화 환산 체결금액'))
    op.alter_column('order_executions', 'execution_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=20, scale=8),
               comment='체결가격 (현지통화)',
               existing_comment='체결가격',
               existing_nullable=False)
    op.alter_column('order_executions', 'execution_quantity',
               existing_type=mysql.DECIMAL(precision=20, scale=0),
               type_=sa.Numeric(precision=20, scale=8),
               existing_comment='체결수량',
               existing_nullable=False)
    op.alter_column('order_executions', 'execution_amount',
               existing_type=mysql.DECIMAL(precision=20, scale=2),
               type_=sa.Numeric(precision=20, scale=8),
               comment='체결금액 (현지통화)',
               existing_comment='체결금액',
               existing_nullable=False)
    op.alter_column('order_executions', 'execution_fee',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=20, scale=8),
               existing_comment='체결 수수료',
               existing_nullable=False)
    op.add_column('orders', sa.Column('product_code', sa.String(length=20), nullable=False, comment='상품 코드 (주식: 005930, 해외주식: AAPL, 코인: BTC-KRW)'))
    op.add_column('orders', sa.Column('product_name', sa.String(length=100), nullable=False, comment='상품명 (삼성전자, Apple Inc., 비트코인)'))
    op.add_column('orders', sa.Column('market', sa.String(length=50), nullable=False, comment='시장/거래소 (KOSPI, NYSE, NASDAQ, Upbit)'))
    op.add_column('orders', sa.Column('currency', sa.String(length=10), nullable=False, comment='주문 통화 (KRW/USD/EUR/JPY)'))
    op.add_column('orders', sa.Column('exchange_rate', sa.Numeric(precision=10, scale=4), nullable=True, comment='거래 시점 환율 (외화 -> KRW)'))
    op.add_column('orders', sa.Column('krw_order_price', sa.Numeric(precision=20, scale=2), nullable=True, comment='원화 환산 주문가격'))
    op.add_column('orders', sa.Column('krw_executed_amount', sa.Numeric(precision=20, scale=2), nullable=True, comment='원화 환산 체결금액'))
    op.alter_column('orders', 'order_method',
               existing_type=mysql.ENUM('MARKET', 'LIMIT', 'STOP_LOSS', 'TAKE_PROFIT', collation='utf8mb3_unicode_ci'),
               comment='주문 방식 (MARKET/LIMIT)',
               existing_comment='주문 방식 (MARKET/LIMIT/STOP_LOSS/TAKE_PROFIT)',
               existing_nullable=False)
    op.alter_column('orders', 'quantity',
               existing_type=mysql.DECIMAL(precision=20, scale=0),
               type_=sa.Numeric(precision=20, scale=8),
               comment='주문 수량 (코인: 소수점 8자리)',
               existing_comment='주문 수량',
               existing_nullable=False)
    op.alter_column('orders', 'order_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=20, scale=8),
               comment='주문 가격 (원화 또는 현지통화)',
               existing_comment='주문 가격 (지정가 주문시)',
               existing_nullable=True)
    op.alter_column('orders', 'executed_quantity',
               existing_type=mysql.DECIMAL(precision=20, scale=0),
               type_=sa.Numeric(precision=20, scale=8),
               existing_comment='체결된 수량',
               existing_nullable=False)
    op.alter_column('orders', 'executed_amount',
               existing_type=mysql.DECIMAL(precision=20, scale=2),
               type_=sa.Numeric(precision=20, scale=8),
               comment='체결된 금액 (현지통화)',
               existing_comment='체결된 금액',
               existing_nullable=False)
    op.alter_column('orders', 'average_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=20, scale=8),
               comment='평균 체결가 (현지통화)',
               existing_comment='평균 체결가',
               existing_nullable=True)
    op.drop_column('orders', 'stock_id')
    op.add_column('portfolios', sa.Column('product_code', sa.String(length=20), nullable=False, comment='상품 코드 (주식: A005930, 코인: BTC-KRW)'))
    op.add_column('portfolios', sa.Column('product_name', sa.String(length=100), nullable=False, comment='상품명 (삼성전자, 비트코인)'))
    op.add_column('portfolios', sa.Column('product_type', sa.Enum('STOCK', 'CRYPTO', name='producttype'), nullable=False, comment='자산 유형 (STOCK/CRYPTO)'))
    op.add_column('portfolios', sa.Column('market', sa.String(length=50), nullable=False, comment='시장/거래소 (KOSPI, NASDAQ, Upbit, Binance)'))
    op.add_column('portfolios', sa.Column('symbol', sa.String(length=10), nullable=True, comment='코인 심볼 (BTC, ETH, ADA)'))
    op.add_column('portfolios', sa.Column('base_currency', sa.String(length=10), nullable=True, comment='기준 통화 (KRW, USDT, USD)'))
    op.add_column('portfolios', sa.Column('average_exchange_rate', sa.Numeric(precision=10, scale=4), nullable=True, comment='평균 매수 시점 환율 (외화 -> KRW)'))
    op.add_column('portfolios', sa.Column('krw_average_price', sa.Numeric(precision=20, scale=2), nullable=True, comment='원화 환산 평균 매수가'))
    op.add_column('portfolios', sa.Column('krw_realized_profit_loss', sa.Numeric(precision=20, scale=2), nullable=False, comment='실현 손익 (원화 환산)'))
    op.alter_column('portfolios', 'current_quantity',
               existing_type=mysql.DECIMAL(precision=20, scale=0),
               type_=sa.Numeric(precision=20, scale=8),
               comment='현재 보유 수량 (코인: 소수점 8자리)',
               existing_comment='현재 보유 수량',
               existing_nullable=False)
    op.alter_column('portfolios', 'average_price',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Numeric(precision=20, scale=8),
               comment='평균 매수가 (현지통화 기준)',
               existing_comment='평균 매수가',
               existing_nullable=False)
    op.alter_column('portfolios', 'realized_profit_loss',
               existing_type=mysql.DECIMAL(precision=20, scale=2),
               type_=sa.Numeric(precision=20, scale=8),
               comment='실현 손익 (현지통화 기준)',
               existing_comment='실현 손익',
               existing_nullable=False)
    op.drop_column('portfolios', 'stock_id')
    op.alter_column('watch_lists', 'product_code',
               existing_type=mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=20),
               comment='상품 코드 (주식, 코인 등 - 예: 097230, BTC-KRW)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watch_lists', 'product_code',
               existing_type=mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=20),
               comment=None,
               existing_comment='상품 코드 (주식, 코인 등 - 예: 097230, BTC-KRW)',
               existing_nullable=False)
    op.add_column('portfolios', sa.Column('stock_id', mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=20), nullable=False, comment='주식 종목 코드 (예: 097230)'))
    op.alter_column('portfolios', 'realized_profit_loss',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=mysql.DECIMAL(precision=20, scale=2),
               comment='실현 손익',
               existing_comment='실현 손익 (현지통화 기준)',
               existing_nullable=False)
    op.alter_column('portfolios', 'average_price',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=mysql.DECIMAL(precision=10, scale=2),
               comment='평균 매수가',
               existing_comment='평균 매수가 (현지통화 기준)',
               existing_nullable=False)
    op.alter_column('portfolios', 'current_quantity',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=mysql.DECIMAL(precision=20, scale=0),
               comment='현재 보유 수량',
               existing_comment='현재 보유 수량 (코인: 소수점 8자리)',
               existing_nullable=False)
    op.drop_column('portfolios', 'krw_realized_profit_loss')
    op.drop_column('portfolios', 'krw_average_price')
    op.drop_column('portfolios', 'average_exchange_rate')
    op.drop_column('portfolios', 'base_currency')
    op.drop_column('portfolios', 'symbol')
    op.drop_column('portfolios', 'market')
    op.drop_column('portfolios', 'product_type')
    op.drop_column('portfolios', 'product_name')
    op.drop_column('portfolios', 'product_code')
    op.add_column('orders', sa.Column('stock_id', mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=20), nullable=False, comment='주식 종목 코드 (예: 097230)'))
    op.alter_column('orders', 'average_price',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=mysql.DECIMAL(precision=10, scale=2),
               comment='평균 체결가',
               existing_comment='평균 체결가 (현지통화)',
               existing_nullable=True)
    op.alter_column('orders', 'executed_amount',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=mysql.DECIMAL(precision=20, scale=2),
               comment='체결된 금액',
               existing_comment='체결된 금액 (현지통화)',
               existing_nullable=False)
    op.alter_column('orders', 'executed_quantity',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=mysql.DECIMAL(precision=20, scale=0),
               existing_comment='체결된 수량',
               existing_nullable=False)
    op.alter_column('orders', 'order_price',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=mysql.DECIMAL(precision=10, scale=2),
               comment='주문 가격 (지정가 주문시)',
               existing_comment='주문 가격 (원화 또는 현지통화)',
               existing_nullable=True)
    op.alter_column('orders', 'quantity',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=mysql.DECIMAL(precision=20, scale=0),
               comment='주문 수량',
               existing_comment='주문 수량 (코인: 소수점 8자리)',
               existing_nullable=False)
    op.alter_column('orders', 'order_method',
               existing_type=mysql.ENUM('MARKET', 'LIMIT', 'STOP_LOSS', 'TAKE_PROFIT', collation='utf8mb3_unicode_ci'),
               comment='주문 방식 (MARKET/LIMIT/STOP_LOSS/TAKE_PROFIT)',
               existing_comment='주문 방식 (MARKET/LIMIT)',
               existing_nullable=False)
    op.drop_column('orders', 'krw_executed_amount')
    op.drop_column('orders', 'krw_order_price')
    op.drop_column('orders', 'exchange_rate')
    op.drop_column('orders', 'currency')
    op.drop_column('orders', 'market')
    op.drop_column('orders', 'product_name')
    op.drop_column('orders', 'product_code')
    op.alter_column('order_executions', 'execution_fee',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_comment='체결 수수료',
               existing_nullable=False)
    op.alter_column('order_executions', 'execution_amount',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=mysql.DECIMAL(precision=20, scale=2),
               comment='체결금액',
               existing_comment='체결금액 (현지통화)',
               existing_nullable=False)
    op.alter_column('order_executions', 'execution_quantity',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=mysql.DECIMAL(precision=20, scale=0),
               existing_comment='체결수량',
               existing_nullable=False)
    op.alter_column('order_executions', 'execution_price',
               existing_type=sa.Numeric(precision=20, scale=8),
               type_=mysql.DECIMAL(precision=10, scale=2),
               comment='체결가격',
               existing_comment='체결가격 (현지통화)',
               existing_nullable=False)
    op.drop_column('order_executions', 'krw_execution_amount')
    op.drop_column('order_executions', 'krw_execution_price')
    op.drop_column('order_executions', 'exchange_rate')
    # ### end Alembic commands ###
