"""portfolio에서 실현손익 컬럼 제거

Revision ID: 5d3600b86857
Revises: 536869bfd17a
Create Date: 2025-09-04 20:32:50.113782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5d3600b86857'
down_revision: Union[str, Sequence[str], None] = '536869bfd17a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'realized_profit_loss')
    op.drop_column('portfolios', 'krw_realized_profit_loss')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('krw_realized_profit_loss', mysql.DECIMAL(precision=20, scale=2), nullable=False, comment='실현 손익 (원화 환산)'))
    op.add_column('portfolios', sa.Column('realized_profit_loss', mysql.DECIMAL(precision=20, scale=8), nullable=False, comment='실현 손익 (현지통화 기준)'))
    # ### end Alembic commands ###
