"""Add foreign key constraints to user related tables

Revision ID: 62b9b0b1b00a
Revises: 97be0572c6a8
Create Date: 2025-08-07 16:13:22.737494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62b9b0b1b00a'
down_revision: Union[str, Sequence[str], None] = '97be0572c6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'order_executions', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'stocks', ['stock_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'portfolios', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'portfolios', 'stocks', ['stock_id'], ['id'])
    op.create_foreign_key(None, 'trading_statistics', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'stocks', ['stock_id'], ['id'])
    op.create_foreign_key(None, 'virtual_balance_histories', 'virtual_balances', ['virtual_balance_id'], ['id'])
    op.create_foreign_key(None, 'virtual_balance_histories', 'orders', ['related_order_id'], ['id'])
    op.create_foreign_key(None, 'virtual_balances', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'watch_lists', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'watch_lists', 'stocks', ['stock_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'watch_lists', type_='foreignkey')
    op.drop_constraint(None, 'watch_lists', type_='foreignkey')
    op.drop_constraint(None, 'virtual_balances', type_='foreignkey')
    op.drop_constraint(None, 'virtual_balance_histories', type_='foreignkey')
    op.drop_constraint(None, 'virtual_balance_histories', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'trading_statistics', type_='foreignkey')
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.drop_constraint(None, 'portfolios', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'order_executions', type_='foreignkey')
    # ### end Alembic commands ###
