"""user에서 kis_app_key, kis_app_secret 를 삭제하고, config 로 이동

Revision ID: 86a6d270bd5b
Revises: f843b672a63d
Create Date: 2025-08-13 22:32:10.087980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '86a6d270bd5b'
down_revision: Union[str, Sequence[str], None] = 'f843b672a63d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kis_app_key')
    op.drop_column('users', 'kis_app_secret')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kis_app_secret', mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=255), nullable=True, comment='KIS APP SECRET'))
    op.add_column('users', sa.Column('kis_app_key', mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=255), nullable=True, comment='KIS APP KEY'))
    # ### end Alembic commands ###
