"""Initial migration: Create all tables

Revision ID: 97be0572c6a8
Revises: 
Create Date: 2025-08-07 11:43:07.163771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '97be0572c6a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_executions',
    sa.Column('order_id', sa.String(length=36), nullable=False, comment='주문 ID'),
    sa.Column('execution_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='체결가격'),
    sa.Column('execution_quantity', sa.Numeric(precision=20, scale=0), nullable=False, comment='체결수량'),
    sa.Column('execution_amount', sa.Numeric(precision=20, scale=2), nullable=False, comment='체결금액'),
    sa.Column('execution_time', sa.DateTime(), nullable=False, comment='체결시간'),
    sa.Column('execution_fee', sa.Numeric(precision=10, scale=2), nullable=False, comment='체결 수수료'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='사용자 ID'),
    sa.Column('stock_id', sa.String(length=36), nullable=False, comment='주식 종목 ID'),
    sa.Column('order_type', sa.Enum('BUY', 'SELL', name='ordertype'), nullable=False, comment='주문 유형 (BUY/SELL)'),
    sa.Column('order_method', sa.Enum('MARKET', 'LIMIT', 'STOP_LOSS', 'TAKE_PROFIT', name='ordermethod'), nullable=False, comment='주문 방식 (MARKET/LIMIT/STOP_LOSS/TAKE_PROFIT)'),
    sa.Column('order_status', sa.Enum('PENDING', 'PARTIALLY_FILLED', 'FILLED', 'CANCELLED', 'REJECTED', 'EXPIRED', name='orderstatus'), nullable=False, comment='주문 상태'),
    sa.Column('quantity', sa.Numeric(precision=20, scale=0), nullable=False, comment='주문 수량'),
    sa.Column('order_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='주문 가격 (지정가 주문시)'),
    sa.Column('executed_quantity', sa.Numeric(precision=20, scale=0), nullable=False, comment='체결된 수량'),
    sa.Column('executed_amount', sa.Numeric(precision=20, scale=2), nullable=False, comment='체결된 금액'),
    sa.Column('average_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='평균 체결가'),
    sa.Column('commission', sa.Numeric(precision=10, scale=2), nullable=False, comment='거래 수수료'),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False, comment='거래세'),
    sa.Column('total_fee', sa.Numeric(precision=10, scale=2), nullable=False, comment='총 수수료'),
    sa.Column('order_date', sa.DateTime(), nullable=False, comment='주문일시'),
    sa.Column('executed_date', sa.DateTime(), nullable=True, comment='체결일시'),
    sa.Column('cancelled_date', sa.DateTime(), nullable=True, comment='취소일시'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='주문 만료일시'),
    sa.Column('notes', sa.Text(), nullable=True, comment='주문 메모'),
    sa.Column('is_simulated', sa.Boolean(), nullable=False, comment='가상거래 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='사용자 ID'),
    sa.Column('stock_id', sa.String(length=36), nullable=False, comment='주식 종목 ID'),
    sa.Column('quantity', sa.Numeric(precision=20, scale=0), nullable=False, comment='보유 수량'),
    sa.Column('average_buy_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='평균 매수가'),
    sa.Column('total_buy_amount', sa.Numeric(precision=20, scale=2), nullable=False, comment='총 매수금액'),
    sa.Column('current_value', sa.Numeric(precision=20, scale=2), nullable=True, comment='현재 평가금액'),
    sa.Column('unrealized_profit_loss', sa.Numeric(precision=20, scale=2), nullable=True, comment='미실현 손익'),
    sa.Column('unrealized_profit_loss_rate', sa.Numeric(precision=5, scale=2), nullable=True, comment='미실현 손익률 (%)'),
    sa.Column('realized_profit_loss', sa.Numeric(precision=20, scale=2), nullable=False, comment='실현 손익'),
    sa.Column('first_buy_date', sa.DateTime(), nullable=False, comment='최초 매수일'),
    sa.Column('last_buy_date', sa.DateTime(), nullable=True, comment='최근 매수일'),
    sa.Column('last_sell_date', sa.DateTime(), nullable=True, comment='최근 매도일'),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False, comment='마지막 업데이트 시간'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 보유 여부'),
    sa.Column('notes', sa.Text(), nullable=True, comment='포트폴리오 메모'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('stock_prices',
    sa.Column('stock_id', sa.String(length=36), nullable=False, comment='주식 종목 ID'),
    sa.Column('open_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='시가'),
    sa.Column('high_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='고가'),
    sa.Column('low_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='저가'),
    sa.Column('close_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='종가'),
    sa.Column('current_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='현재가'),
    sa.Column('volume', sa.Numeric(precision=20, scale=0), nullable=False, comment='거래량'),
    sa.Column('trading_value', sa.Numeric(precision=20, scale=2), nullable=False, comment='거래대금'),
    sa.Column('price_change', sa.Numeric(precision=10, scale=2), nullable=False, comment='전일 대비 가격 변동'),
    sa.Column('price_change_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='전일 대비 변동률 (%)'),
    sa.Column('price_date', sa.DateTime(), nullable=False, comment='가격 기준일시'),
    sa.Column('is_real_time', sa.Boolean(), nullable=False, comment='실시간 데이터 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks',
    sa.Column('code', sa.String(length=20), nullable=False, comment='주식 종목 코드 (예: 005930)'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='주식 종목명 (예: 삼성전자)'),
    sa.Column('market', sa.String(length=20), nullable=False, comment='시장 구분 (KOSPI, KOSDAQ, NASDAQ 등)'),
    sa.Column('sector', sa.String(length=50), nullable=True, comment='업종'),
    sa.Column('industry', sa.String(length=100), nullable=True, comment='세부 업종'),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=True, comment='시가총액'),
    sa.Column('listed_shares', sa.Numeric(precision=20, scale=0), nullable=True, comment='상장 주식 수'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='거래 활성화 여부'),
    sa.Column('listing_date', sa.DateTime(), nullable=True, comment='상장일'),
    sa.Column('description', sa.Text(), nullable=True, comment='종목 설명'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('trading_statistics',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='사용자 ID'),
    sa.Column('period_type', sa.String(length=10), nullable=False, comment='기간 유형 (daily/weekly/monthly/yearly)'),
    sa.Column('period_start', sa.DateTime(), nullable=False, comment='기간 시작일'),
    sa.Column('period_end', sa.DateTime(), nullable=False, comment='기간 종료일'),
    sa.Column('total_trades', sa.Numeric(precision=10, scale=0), nullable=False, comment='총 거래 횟수'),
    sa.Column('buy_trades', sa.Numeric(precision=10, scale=0), nullable=False, comment='매수 거래 횟수'),
    sa.Column('sell_trades', sa.Numeric(precision=10, scale=0), nullable=False, comment='매도 거래 횟수'),
    sa.Column('total_buy_amount', sa.Numeric(precision=20, scale=2), nullable=False, comment='총 매수 금액'),
    sa.Column('total_sell_amount', sa.Numeric(precision=20, scale=2), nullable=False, comment='총 매도 금액'),
    sa.Column('total_commission', sa.Numeric(precision=10, scale=2), nullable=False, comment='총 수수료'),
    sa.Column('total_tax', sa.Numeric(precision=10, scale=2), nullable=False, comment='총 세금'),
    sa.Column('realized_profit_loss', sa.Numeric(precision=20, scale=2), nullable=False, comment='실현 손익'),
    sa.Column('win_trades', sa.Numeric(precision=10, scale=0), nullable=False, comment='수익 거래 횟수'),
    sa.Column('loss_trades', sa.Numeric(precision=10, scale=0), nullable=False, comment='손실 거래 횟수'),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='승률 (%)'),
    sa.Column('portfolio_value_start', sa.Numeric(precision=20, scale=2), nullable=False, comment='기간 시작시 포트폴리오 가치'),
    sa.Column('portfolio_value_end', sa.Numeric(precision=20, scale=2), nullable=False, comment='기간 종료시 포트폴리오 가치'),
    sa.Column('portfolio_return', sa.Numeric(precision=5, scale=2), nullable=False, comment='포트폴리오 수익률 (%)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='사용자 ID'),
    sa.Column('stock_id', sa.String(length=36), nullable=True, comment='주식 종목 ID (주식 거래시)'),
    sa.Column('order_id', sa.String(length=36), nullable=True, comment='주문 ID (주문 관련 거래시)'),
    sa.Column('transaction_type', sa.Enum('BUY', 'SELL', 'DIVIDEND', 'DEPOSIT', 'WITHDRAW', 'FEE', 'TAX', name='transactiontype'), nullable=False, comment='거래 유형'),
    sa.Column('quantity', sa.Numeric(precision=20, scale=0), nullable=True, comment='거래 수량 (주식 거래시)'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True, comment='거래가격 (주식 거래시)'),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False, comment='거래금액'),
    sa.Column('commission', sa.Numeric(precision=10, scale=2), nullable=False, comment='수수료'),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False, comment='세금'),
    sa.Column('net_amount', sa.Numeric(precision=20, scale=2), nullable=False, comment='순 거래금액 (수수료, 세금 제외)'),
    sa.Column('cash_balance_before', sa.Numeric(precision=20, scale=2), nullable=False, comment='거래 전 현금 잔고'),
    sa.Column('cash_balance_after', sa.Numeric(precision=20, scale=2), nullable=False, comment='거래 후 현금 잔고'),
    sa.Column('transaction_date', sa.DateTime(), nullable=False, comment='거래일시'),
    sa.Column('settlement_date', sa.DateTime(), nullable=True, comment='결제일 (T+2)'),
    sa.Column('description', sa.Text(), nullable=True, comment='거래 설명'),
    sa.Column('reference_number', sa.String(length=50), nullable=True, comment='참조번호'),
    sa.Column('is_simulated', sa.Boolean(), nullable=False, comment='가상거래 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('userid', sa.String(length=255), nullable=False, comment='유저 고유 아이디'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='이메일'),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=True, comment='전화번호'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='user 이름'),
    sa.Column('sign_in_count', sa.Integer(), nullable=False),
    sa.Column('last_sign_in_at', sa.DateTime(), nullable=True, comment='마지막 로그인 시간'),
    sa.Column('last_sign_in_ip', sa.String(length=255), nullable=True, comment='마지막 로그인 아이피'),
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.Column('refresh_token', sa.String(length=255), nullable=False, comment='refresh token'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('avatar_url', sa.String(length=255), nullable=True, comment='프로필 이미지'),
    sa.Column('exposure', sa.Integer(), nullable=True, comment='노출여부'),
    sa.Column('uuid', sa.String(length=255), nullable=True, comment='SNS id or random generated uuid'),
    sa.Column('sign_up_from', sa.String(length=255), nullable=True, comment='SNS(kakao, google, naver, facebook) or stocking'),
    sa.Column('is_admin', sa.Boolean(), nullable=True, comment='어드민여부'),
    sa.Column('push_token', sa.String(length=255), nullable=True, comment='push token'),
    sa.Column('platform', sa.String(length=255), nullable=True, comment='폰 플랫폼'),
    sa.Column('push_on', sa.Boolean(), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('userid')
    )
    op.create_table('virtual_balance_histories',
    sa.Column('virtual_balance_id', sa.String(length=36), nullable=False, comment='가상 잔고 ID'),
    sa.Column('previous_cash_balance', sa.Numeric(precision=20, scale=2), nullable=False, comment='변경 전 현금 잔고'),
    sa.Column('new_cash_balance', sa.Numeric(precision=20, scale=2), nullable=False, comment='변경 후 현금 잔고'),
    sa.Column('change_amount', sa.Numeric(precision=20, scale=2), nullable=False, comment='변경 금액'),
    sa.Column('change_type', sa.String(length=20), nullable=False, comment='변경 유형 (BUY/SELL/DEPOSIT/WITHDRAW)'),
    sa.Column('related_order_id', sa.String(length=36), nullable=True, comment='관련 주문 ID'),
    sa.Column('description', sa.Text(), nullable=True, comment='변경 설명'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('virtual_balances',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='사용자 ID'),
    sa.Column('cash_balance', sa.Numeric(precision=20, scale=2), nullable=False, comment='현금 잔고'),
    sa.Column('invested_amount', sa.Numeric(precision=20, scale=2), nullable=False, comment='투자 금액'),
    sa.Column('total_portfolio_value', sa.Numeric(precision=20, scale=2), nullable=False, comment='총 포트폴리오 가치'),
    sa.Column('total_asset_value', sa.Numeric(precision=20, scale=2), nullable=False, comment='총 자산 가치 (현금 + 포트폴리오)'),
    sa.Column('total_profit_loss', sa.Numeric(precision=20, scale=2), nullable=False, comment='총 손익'),
    sa.Column('total_profit_loss_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='총 손익률 (%)'),
    sa.Column('daily_profit_loss', sa.Numeric(precision=20, scale=2), nullable=False, comment='일일 손익'),
    sa.Column('daily_profit_loss_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='일일 손익률 (%)'),
    sa.Column('total_buy_amount', sa.Numeric(precision=20, scale=2), nullable=False, comment='총 매수 금액'),
    sa.Column('total_sell_amount', sa.Numeric(precision=20, scale=2), nullable=False, comment='총 매도 금액'),
    sa.Column('total_commission', sa.Numeric(precision=10, scale=2), nullable=False, comment='총 수수료'),
    sa.Column('total_tax', sa.Numeric(precision=10, scale=2), nullable=False, comment='총 세금'),
    sa.Column('last_trade_date', sa.DateTime(), nullable=True, comment='마지막 거래일'),
    sa.Column('last_updated_at', sa.DateTime(), nullable=False, comment='마지막 업데이트 시간'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('watch_lists',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='사용자 ID'),
    sa.Column('stock_id', sa.String(length=36), nullable=False, comment='주식 종목 ID'),
    sa.Column('add_date', sa.DateTime(), nullable=False, comment='추가일'),
    sa.Column('target_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='목표가'),
    sa.Column('stop_loss_price', sa.Numeric(precision=10, scale=2), nullable=True, comment='손절가'),
    sa.Column('memo', sa.Text(), nullable=True, comment='메모'),
    sa.Column('price_alert_enabled', sa.Boolean(), nullable=False, comment='가격 알림 활성화'),
    sa.Column('price_alert_upper', sa.Numeric(precision=10, scale=2), nullable=True, comment='상한 알림가'),
    sa.Column('price_alert_lower', sa.Numeric(precision=10, scale=2), nullable=True, comment='하한 알림가'),
    sa.Column('volume_alert_enabled', sa.Boolean(), nullable=False, comment='거래량 알림 활성화'),
    sa.Column('volume_alert_threshold', sa.Numeric(precision=20, scale=0), nullable=True, comment='거래량 알림 기준'),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='표시 순서'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='카테고리'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('user_id', mysql.CHAR(length=36), nullable=True, comment='작성자 ID'),
    sa.Column('commentable_id', mysql.CHAR(length=36), nullable=False, comment='코멘트 대상 ID'),
    sa.Column('commentable_type', sa.String(length=255), nullable=False, comment='코멘트 대상 타입'),
    sa.Column('content', sa.Text(), nullable=False, comment='코멘트 내용'),
    sa.Column('ancestry', sa.String(length=255), nullable=True, comment='계층 구조 경로'),
    sa.Column('ancestry_depth', sa.Integer(), nullable=True, comment='계층 깊이 캐시'),
    sa.Column('children_count', sa.Integer(), nullable=True, comment='하위 코멘트 수 캐시'),
    sa.Column('is_question', sa.Boolean(), nullable=True, comment='질문이면 True, 답변이면 False'),
    sa.Column('answer_name', sa.String(length=255), nullable=True, comment='답변한 사람, card package 주인 혹은 system 관리자(CS)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notices',
    sa.Column('creator_id', mysql.CHAR(length=36), nullable=False, comment='생성자 ID'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='제목'),
    sa.Column('content', sa.Text(), nullable=False, comment='내용'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성화 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('user_id', mysql.CHAR(length=36), nullable=False, comment='신고한 사용자'),
    sa.Column('reportable_type', sa.String(length=50), nullable=False, comment='신고 대상 유형(verification, user, etc)'),
    sa.Column('reportable_id', mysql.CHAR(length=36), nullable=False, comment='신고 대상 ID'),
    sa.Column('reason', sa.String(length=255), nullable=False, comment='신고 이유'),
    sa.Column('description', sa.Text(), nullable=True, comment='신고 세부 내용'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='처리 상태: pending, in_progress, resolved'),
    sa.Column('handled_by', sa.String(length=36), nullable=True, comment='처리자(운영자) ID'),
    sa.Column('handled_at', sa.DateTime(), nullable=True, comment='처리 시각'),
    sa.Column('handler_comment', sa.Text(), nullable=True, comment='처리자가 남긴 코멘트/메모'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_id', sa.String(length=36), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report_status_histories',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('handled_by', sa.String(length=36), nullable=False),
    sa.Column('handler_comment', sa.Text(), nullable=True),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_status_histories')
    op.drop_table('user_roles')
    op.drop_table('reports')
    op.drop_table('notices')
    op.drop_table('comments')
    op.drop_table('watch_lists')
    op.drop_table('virtual_balances')
    op.drop_table('virtual_balance_histories')
    op.drop_table('users')
    op.drop_table('transactions')
    op.drop_table('trading_statistics')
    op.drop_table('stocks')
    op.drop_table('stock_prices')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('portfolios')
    op.drop_table('orders')
    op.drop_table('order_executions')
    # ### end Alembic commands ###
