"""user에서 kis_approval_key 키 제거

Revision ID: 9e62fccaa8e6
Revises: 86a6d270bd5b
Create Date: 2025-08-13 23:11:56.559387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9e62fccaa8e6'
down_revision: Union[str, Sequence[str], None] = '86a6d270bd5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kis_token_updated_at')
    op.drop_column('users', 'kis_access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kis_access_token', mysql.VARCHAR(collation='utf8mb3_unicode_ci', length=255), nullable=True, comment='KIS websocket approval key'))
    op.add_column('users', sa.Column('kis_token_updated_at', mysql.DATETIME(), nullable=True, comment='KIS token last updated at'))
    # ### end Alembic commands ###
