"""Update portfolio model fields

Revision ID: a5652e650f2b
Revises: 409e0668d264
Create Date: 2025-08-07 18:22:00.319943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a5652e650f2b'
down_revision: Union[str, Sequence[str], None] = '409e0668d264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('current_quantity', sa.Numeric(precision=20, scale=0), nullable=False, comment='현재 보유 수량'))
    op.add_column('portfolios', sa.Column('total_quantity', sa.Numeric(precision=20, scale=0), nullable=False, comment='총 매수 수량'))
    op.add_column('portfolios', sa.Column('average_price', sa.Numeric(precision=10, scale=2), nullable=False, comment='평균 매수가'))
    op.add_column('portfolios', sa.Column('total_invested_amount', sa.Numeric(precision=20, scale=2), nullable=False, comment='총 투자금액'))
    op.drop_column('portfolios', 'average_buy_price')
    op.drop_column('portfolios', 'quantity')
    op.drop_column('portfolios', 'total_buy_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('total_buy_amount', mysql.DECIMAL(precision=20, scale=2), nullable=False, comment='총 매수금액'))
    op.add_column('portfolios', sa.Column('quantity', mysql.DECIMAL(precision=20, scale=0), nullable=False, comment='보유 수량'))
    op.add_column('portfolios', sa.Column('average_buy_price', mysql.DECIMAL(precision=10, scale=2), nullable=False, comment='평균 매수가'))
    op.drop_column('portfolios', 'total_invested_amount')
    op.drop_column('portfolios', 'average_price')
    op.drop_column('portfolios', 'total_quantity')
    op.drop_column('portfolios', 'current_quantity')
    # ### end Alembic commands ###
