"""가상잔고 업데이트

Revision ID: a62ef903a48e
Revises: b905c3740963
Create Date: 2025-08-07 16:37:59.207444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a62ef903a48e'
down_revision: Union[str, Sequence[str], None] = 'b905c3740963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtual_balances', sa.Column('available_cash', sa.Numeric(precision=20, scale=2), nullable=False, comment='사용 가능한 현금 (주문 대기 중인 금액 제외)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtual_balances', 'available_cash')
    # ### end Alembic commands ###
