"""add_total_buy_amount_to_portfolio

Revision ID: b21471c9346b
Revises: 4f7473bdd1af
Create Date: 2025-09-05 16:42:42.290719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b21471c9346b'
down_revision: Union[str, Sequence[str], None] = '4f7473bdd1af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('total_buy_amount', sa.Numeric(precision=20, scale=8), nullable=False, comment='총 구매금액 (현지통화 기준)'))
    op.add_column('portfolios', sa.Column('krw_total_buy_amount', sa.Numeric(precision=20, scale=2), nullable=True, comment='원화 환산 총 구매금액'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'krw_total_buy_amount')
    op.drop_column('portfolios', 'total_buy_amount')
    # ### end Alembic commands ###
