"""portfolios 테이블에 industry_code VARCHAR(50) NULL, industry_display VARCHAR(100) NULL 컬럼 추가

Revision ID: b68e52d816cc
Revises: b21471c9346b
Create Date: 2025-09-08 20:30:06.645139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b68e52d816cc'
down_revision: Union[str, Sequence[str], None] = 'b21471c9346b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('industry_code', sa.String(length=50), nullable=True, comment='업종 코드'))
    op.add_column('portfolios', sa.Column('industry_display', sa.String(length=100), nullable=True, comment='업종명'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'industry_display')
    op.drop_column('portfolios', 'industry_code')
    # ### end Alembic commands ###
