"""StockPrice.stock_id에 ForeignKey('stocks.id') 추가


Revision ID: b905c3740963
Revises: 62b9b0b1b00a
Create Date: 2025-08-07 16:15:07.719835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b905c3740963'
down_revision: Union[str, Sequence[str], None] = '62b9b0b1b00a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'stock_prices', 'stocks', ['stock_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_prices', type_='foreignkey')
    # ### end Alembic commands ###
