"""exit_reason 추가

Revision ID: ba57019f51e7
Revises: 8d5428a8fb13
Create Date: 2025-08-11 14:45:10.991912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba57019f51e7'
down_revision: Union[str, Sequence[str], None] = '8d5428a8fb13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('exit_reason', sa.Enum('STOP_LOSS', 'TAKE_PROFIT', name='exitreason'), nullable=True, comment='매도 사유 (SELL 주문시: STOP_LOSS/TAKE_PROFIT)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'exit_reason')
    # ### end Alembic commands ###
