"""user에 kis token 필드 추가

Revision ID: f843b672a63d
Revises: 0bbb617f58e3
Create Date: 2025-08-13 22:15:51.619480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f843b672a63d'
down_revision: Union[str, Sequence[str], None] = '0bbb617f58e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('kis_app_key', sa.String(length=255), nullable=True, comment='KIS APP KEY'))
    op.add_column('users', sa.Column('kis_app_secret', sa.String(length=255), nullable=True, comment='KIS APP SECRET'))
    op.add_column('users', sa.Column('kis_access_token', sa.String(length=255), nullable=True, comment='KIS websocket approval key'))
    op.add_column('users', sa.Column('kis_token_updated_at', sa.DateTime(), nullable=True, comment='KIS token last updated at'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'kis_token_updated_at')
    op.drop_column('users', 'kis_access_token')
    op.drop_column('users', 'kis_app_secret')
    op.drop_column('users', 'kis_app_key')
    # ### end Alembic commands ###
