version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "network-infrastructure"
s3_bucket = "aws-sam-cli-keauty"
s3_prefix = "network-infrastructure"
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev VpcCIDR=10.0.0.0/16 PublicSubnet1CIDR=10.0.1.0/24 PublicSubnet2CIDR=10.0.2.0/24 PrivateSubnet1CIDR=10.0.3.0/24 PrivateSubnet2CIDR=10.0.4.0/24 AvailabilityZone1=ap-northeast-2a AvailabilityZone2=ap-northeast-2b"
confirm_changeset = true
disable_rollback = false

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "network-infrastructure-staging"
parameter_overrides = "Environment=staging VpcCIDR=10.1.0.0/16 PublicSubnet1CIDR=10.1.1.0/24 PublicSubnet2CIDR=10.1.2.0/24 PrivateSubnet1CIDR=10.1.3.0/24 PrivateSubnet2CIDR=10.1.4.0/24 AvailabilityZone1=ap-northeast-2a AvailabilityZone2=ap-northeast-2b"

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "network-infrastructure-prod"
parameter_overrides = "Environment=prod VpcCIDR=10.2.0.0/16 PublicSubnet1CIDR=10.2.1.0/24 PublicSubnet2CIDR=10.2.2.0/24 PrivateSubnet1CIDR=10.2.3.0/24 PrivateSubnet2CIDR=10.2.4.0/24 AvailabilityZone1=ap-northeast-2a AvailabilityZone2=ap-northeast-2b"
