version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "kayty-s3-cloudfront"
s3_bucket = "aws-sam-cli-keauty"
s3_prefix = "kayty-s3-cloudfront"
region = "ap-northeast-2"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BucketName=kayty AllowedOrigins=* DomainName=kayty.kr AcmCertificateArn=arn:aws:acm:us-east-1:775405889390:certificate/38a4edfd-1f20-4914-a7af-6e85ea47a655"
confirm_changeset = true
disable_rollback = false

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "kayty-s3-cloudfront-dev"
parameter_overrides = "BucketName=kayty-dev AllowedOrigins=*"

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "kayty-s3-cloudfront-staging"
parameter_overrides = "BucketName=kayty-staging AllowedOrigins=*"

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "kayty-s3-cloudfront-prod"
parameter_overrides = "BucketName=kayty-prod AllowedOrigins=*"
